name: rocket_gps
description: "A GPS tracking app for bluetooth classic Rocketry GPS devices."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bluetooth_classic: ^0.0.2
  external_path: ^2.0.1
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  map_launcher: ^3.1.0
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/